### PR TITLE
added coffee cjsx syntax highlighting

### PR DESCRIPTION
**Pull request by crisward**
This was taken from https://github.com/reactjs/sublime-react/

The pull request was suggested here https://github.com/babel/babel-sublime/issues/96

### CODE REVIEW

**Comment by chrisvfritz** [comment]
:+1:

**Comment by kwood** [comment]
Hopefully @aponxi can chime in and let us know whether better-coffeescript is interested in hosting the CJSX definitions. If not, [sublime-cjsx](https://github.com/Guidebook/sublime-cjsx) can be [merged into package control](https://github.com/wbond/package_control_channel/pull/4352).

If it is to be supported in this repo, I think we'd want [this commit](https://github.com/aponxi/sublime-better-coffeescript/commit/00a38dce82bfbc4d02be37c9ad9f77d36fb979df) reverted, and [HTML attribute tags](https://github.com/Guidebook/sublime-cjsx/commit/77e396255d877816df74d13dbebc40e306319041) receive syntax highlighting as well.

**Comment by jamesfzhang** [comment]
When does this plan on getting merged?

**Comment by kwood** [comment]
@jamesfzhang this repo appears to be on ice, but you can install [sublime-cjsx](https://github.com/Guidebook/sublime-cjsx) from package control to get CJSX highlighting.

**Comment by jamesfzhang** [comment]
@kwood Thanks for the tip!

**Comment by binarykitchen** [comment]
merge and publish this please!

**Pull request closed without merging**
